// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'form': string;
  'input': string;
  'inputLabel': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
