// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'card': string;
  'card-disabled': string;
  'card-selected': string;
  'container': string;
  'header': string;
  'header_player': string;
}
export const cssExports: CssExports;
export default cssExports;
