// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'action': string;
  'board': string;
  'hand': string;
  'label': string;
  'main': string;
  'stacks': string;
  'status': string;
  'trick': string;
  'trick_zone': string;
}
export const cssExports: CssExports;
export default cssExports;
